version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tmp/docker/mysql:/var/lib/mysql:delegated

  web:
    image: ruby:3.0.1
    command: sh init.sh
    volumes:
      - .:/rails-sample
    working_dir: /rails-sample
    ports:
      - "3000:3000"
    depends_on:
      - db